#!/usr/bin/env bash

set +e

#detecting os
os=linux
if [[ `uname` == 'Darwin' ]]; then
    os=darwin
fi

ANDROID_NDK_VERSION=r13b
INSTALLER_DIR=$HOME/.android-ndk
ANDROID_NDK_ZIP=$HOME/android-ndk.zip
ANDROID_NDK_DIR=$HOME/android-ndk-${ANDROID_NDK_VERSION}

rm -rf $INSTALLER_DIR
rm -rf $ANDROID_NDK_ZIP
rm -rf $ANDROID_NDK_DIR

cd $HOME
wget -q https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-$os-x86_64.zip -O $ANDROID_NDK_ZIP \
    && unzip -q $ANDROID_NDK_ZIP \
    && sync \
    && mv $ANDROID_NDK_DIR $INSTALLER_DIR \
    && rm -rf $ANDROID_NDK_ZIP

